# Generated by Django 6.0.3 on 2026-06-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('release_date', models.DateField()),
                ('director', models.CharField()),
                ('review', models.IntegerField()),
                ('description', models.CharField()),
                ('actor', models.CharField()),
            ],
        ),
    ]
