# Generated by Django 6.0.3 on 2026-07-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cricket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField()),
                ('run', models.IntegerField()),
                ('cap', models.CharField()),
                ('date', models.DateField()),
            ],
        ),
    ]
